// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Spell struct {
	ID        int64 
	Name      string 
	Damage    int64 
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
